apply plugin: 'com.android.application'

android {
    namespace 'com.starcommunication.isp'
    compileSdk 35

    defaultConfig {
        applicationId 'com.starcommunication.isp'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }

    buildTypes {
        debug {
            debuggable true
        }
        release {
            minifyEnabled false
        }
    }
}
